// <auto-generated />
namespace C2C_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CrateTableBuyAndBuyProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrateTableBuyAndBuyProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202007130356292_CrateTableBuyAndBuyProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
